local L = wsLocale:NewLocale("Buzz", "zhCN", true)

L["金币"] = true
L["代练"] = true
L["金库"] = true
L["精灵聊天增强"] = true
L["聊天增强, 聊天快捷键, 过滤关键词"] = true
L["启用聊天过滤"] = true
L["启用聊天过滤, 屏蔽/举报发送垃圾信息玩家"] = true
L["自动举报"] = true
L["开启/关闭自动举报提示框"] = true
L["增减屏蔽关键词"] = true
L["过滤关键词列表, 点击移除"] = true
L["名字着色"] = true
L["启用聊天框玩家名职业着色功能"] = true

L["聊天快捷按钮"] = true
L["启用聊天快捷按钮"] = true
L["说"] = true
L["喊"] = true
L["队"] = true
L["团"] = true
L["警"] = true
L["战"] = true
L["公"] = true
L["官"] = true
L["密"] = true
L["表"] = true
L["综"] = true
L["交"] = "易"
L["寻"] = "组"
L["移动快捷按钮"] = true
L["点击拖动, 双击锁定"] = true

L.Angel="天使"
L.Angry="生气"
L.Biglaugh="大笑"
L.Clap="鼓掌"
L.Cool="酷"
L.Cry="哭"
L.Cute="可爱"
L.Despise="鄙视"
L.Dreamsmile="美梦"
L.Embarras="尴尬"
L.Evil="邪恶"
L.Excited="兴奋"
L.Faint="晕"
L.Fight="打架"
L.Flu="流感"
L.Freeze="呆"
L.Frown="皱眉"
L.Greet="致敬"
L.Grimace="鬼脸"
L.Growl="龇牙"
L.Happy="开心"
L.Heart="心"
L.Horror="恐惧"
L.Ill="生病"
L.Innocent="无辜"
L.Kongfu="功夫"
L.Love="花痴"
L.Mail="邮件"
L.Makeup="化妆"
L.Mario="马里奥"
L.Meditate="沉思"
L.Miserable="可怜"
L.Okay="好"
L.Pretty="漂亮"
L.Puke="吐"
L.Shake="握手"
L.Shout="喊"
L.Silent="闭嘴"
L.Shy="害羞"
L.Sleep="睡觉"
L.Smile="微笑"
L.Suprise="吃惊"
L.Surrender="失败"
L.Sweat="流汗"
L.Tear="流泪"
L.Tears="悲剧"
L.Think="想"
L.Titter="偷笑"
L.Ugly="猥琐"
L.Victory="胜利"
L.Volunteer="雷锋"
L.Wronged="委屈"

