local L = wsLocale:NewLocale("Buzz", "zhTW");

if not L then return end;

L["金币"] = "金幣"
L["代练"] = "代練"
L["金库"] = "金庫"
L["精灵聊天增强"] = "精靈聊天增強"
L["聊天增强, 聊天快捷键, 过滤关键词"] = "聊天增強, 聊天快捷鍵, 過濾垃圾資訊"
L["启用聊天过滤"] = "啟用聊天過濾"
L["启用聊天过滤, 屏蔽/举报发送垃圾信息玩家"] = "啟用聊天過濾, 屏蔽/舉報發送垃圾信息玩家"
L["自动举报"] = "自動舉報"
L["开启/关闭自动举报提示框"] = "開啟/關閉自動舉報提示框"
L["增减屏蔽关键词"] = "增減屏蔽關鍵詞"
L["过滤关键词列表, 点击移除"] = "過濾關鍵詞列表, 點擊移除"
L["名字着色"] = "名字著色"
L["启用聊天框玩家名职业着色功能"] = "啟用聊天框玩家名職業著色功能"

L["聊天快捷按钮"] = "聊天快捷鍵按鈕"
L["启用聊天快捷按钮"] = "啟用聊天快捷鍵按鈕"
L["说"] = "說"
L["喊"] = "喊"
L["队"] = "隊"
L["团"] = "團"
L["警"] = "警"
L["战"] = "戰"
L["公"] = "公"
L["官"] = "官"
L["密"] = "密"
L["表"] = "表"
L["综"] = "綜"
L["交"] = "易"
L["寻"] = "組"
L['转'] = '轉'
L["移动快捷按钮"] = "移動聊天快捷按鈕"
L["点击拖动, 双击锁定"] = "點擊拖動, 雙擊鎖定"
L['启用聊天表情'] = '啟用聊天表情'


L['快捷栏自定义位置'] = '自定義快捷欄位置'
L['不使用固定位置, 可以任意移动, 请用下面选项解锁'] = '不使用固定位置, 可以任意移動, 請用下面選項解鎖'


L.Angel="天使"
L.Angry="生氣"
L.Biglaugh="大笑"
L.Clap="鼓掌"
L.Cool="酷"
L.Cry="哭"
L.Cute="可愛"
L.Despise="鄙視"
L.Dreamsmile="美夢"
L.Embarras="尷尬"
L.Evil="邪惡"
L.Excited="興奮"
L.Faint="暈"
L.Fight="打架"
L.Flu="流感"
L.Freeze="呆"
L.Frown="皺眉"
L.Greet="致敬"
L.Grimace="鬼臉"
L.Growl="齜牙"
L.Happy="開心"
L.Heart="心"
L.Horror="恐懼"
L.Ill="生病"
L.Innocent="無辜"
L.Kongfu="功夫"
L.Love="花癡"
L.Mail="郵件"
L.Makeup="化妝"
L.Mario="馬裏奧"
L.Meditate="沉思"
L.Miserable="可憐"
L.Okay="好"
L.Pretty="漂亮"
L.Puke="吐"
L.Shake="握手"
L.Shout="喊"
L.Silent="閉嘴"
L.Shy="害羞"
L.Sleep="睡覺"
L.Smile="微笑"
L.Suprise="吃驚"
L.Surrender="失敗"
L.Sweat="流汗"
L.Tear="流淚"
L.Tears="悲劇"
L.Think="想"
L.Titter="偷笑"
L.Ugly="猥瑣"
L.Victory="勝利"
L.Volunteer="雷鋒"
L.Wronged="委屈"

