-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/handy-notes_flight-masters/localization/


local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "deDE")
if not L then return end

L["Aldor FlightMaster"] = "Aldor Flugmeister"
L["Alliance FlightMaster"] = "Allianz Flugmeister"
L["Create waypoint"] = "Wegpunkt erstellen"
L["Druid FlightMaster"] = "Druiden Flugmeister"
L["Flight path lines"] = "Fluglinien"
L["FlightMaster Icons"] = "Flugmeister Symbole"
L["FlightMasters"] = "Flugmeister"
L["HandyNotes - FlightMasters"] = "HandyNotes - Flugmeister"
L["Horde FlightMaster"] = "Horde Flugmeister"
L["Icon Alpha"] = "Symboltransparenz"
L["Icon Scale"] = "Symbolgröße"
L["Neutral FlightMaster"] = "Neutraler Flugmeister"
L["PvP FlightMaster"] = "PvP Flugmeister"
L["Scryer FlightMaster"] = "Seher Flugmeister"
L["Show all flightmasters instead of only those that you can use"] = "Zeigt alle Flugmeister, statt nur diejenigen, die Du benutzen kannst."
L["Show both factions"] = "Beide Fraktionen"
L["Show flight path lines"] = "Fluglinien anzeigen"
L["Show flight path lines on the world map"] = "Zeigt Fluglinien auf der Weltkarte an."
L["Show flight path lines on the zone maps as well"] = "Zeigt Fluglinien auf der Zonenkarte an."
L["Show flightmasters on continent level maps as well"] = "Zeigt Flugmeister auch auf Kontinentkarten an."
L["Show in zones"] = "In Zonen anzeigen"
L["Show on continent maps"] = "Auf Kontinentkarten"
L["Skyguard FlightMaster"] = "Himmelswache Flugmeister"
L["The alpha transparency of the icons"] = "Die Transparenz der Symbole."
L["The scale of the icons"] = "Die Größe der Symbole."
L["These settings control the look and feel of the FlightMaster icons."] = "Einstellungen für FlightMaster."


-- vim: ts=4 noexpandtab
