-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/handy-notes_flight-masters/localization/


local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "esES") or LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "esMX")
if not L then return end

-- L["Aldor FlightMaster"] = "Aldor FlightMaster"
-- L["Alliance FlightMaster"] = "Alliance FlightMaster"
-- L["Create waypoint"] = "Create waypoint"
-- L["Druid FlightMaster"] = "Druid FlightMaster"
-- L["Flight path lines"] = "Flight path lines"
-- L["FlightMaster Icons"] = "FlightMaster Icons"
-- L["FlightMasters"] = "FlightMasters"
-- L["HandyNotes - FlightMasters"] = "HandyNotes - FlightMasters"
-- L["Horde FlightMaster"] = "Horde FlightMaster"
-- L["Icon Alpha"] = "Icon Alpha"
-- L["Icon Scale"] = "Icon Scale"
-- L["Neutral FlightMaster"] = "Neutral FlightMaster"
-- L["PvP FlightMaster"] = "PvP FlightMaster"
-- L["Scryer FlightMaster"] = "Scryer FlightMaster"
-- L["Show all flightmasters instead of only those that you can use"] = "Show all flightmasters instead of only those that you can use"
-- L["Show both factions"] = "Show both factions"
-- L["Show flight path lines"] = "Show flight path lines"
-- L["Show flight path lines on the world map"] = "Show flight path lines on the world map"
-- L["Show flight path lines on the zone maps as well"] = "Show flight path lines on the zone maps as well"
-- L["Show flightmasters on continent level maps as well"] = "Show flightmasters on continent level maps as well"
-- L["Show in zones"] = "Show in zones"
-- L["Show on continent maps"] = "Show on continent maps"
-- L["Skyguard FlightMaster"] = "Skyguard FlightMaster"
-- L["The alpha transparency of the icons"] = "The alpha transparency of the icons"
-- L["The scale of the icons"] = "The scale of the icons"
-- L["These settings control the look and feel of the FlightMaster icons."] = "These settings control the look and feel of the FlightMaster icons."


-- vim: ts=4 noexpandtab
