-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/handy-notes_flight-masters/localization/


local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "zhTW")
if not L then return end

L["Aldor FlightMaster"] = "奧多爾飛行管理員"
L["Alliance FlightMaster"] = "聯盟飛行管理員"
L["Create waypoint"] = "建立路徑點"
L["Druid FlightMaster"] = "德魯伊飛行管理員"
L["Flight path lines"] = "飛行路線"
L["FlightMaster Icons"] = "飛行管理員圖示"
L["FlightMasters"] = "飛行管理員"
L["HandyNotes - FlightMasters"] = "HandyNotes - FlightMasters"
L["Horde FlightMaster"] = "部落飛行管理員"
L["Icon Alpha"] = "圖示透明度"
L["Icon Scale"] = "圖示比例"
L["Neutral FlightMaster"] = "中立飛行管理員"
L["PvP FlightMaster"] = "PvP飛行管理員"
L["Scryer FlightMaster"] = "占卜者飛行管理員"
L["Show all flightmasters instead of only those that you can use"] = "顯示所有飛行管理員而不只是顯示你能使用的"
L["Show both factions"] = "顯示雙方陣營"
L["Show flight path lines"] = "顯示飛行路線"
L["Show flight path lines on the world map"] = "在世界地圖上顯示飛行路線"
L["Show flight path lines on the zone maps as well"] = "在區域地圖中也顯示飛行路線"
L["Show flightmasters on continent level maps as well"] = "在大陸地圖上也顯示飛行路線"
L["Show in zones"] = "在地區中顯示"
L["Show on continent maps"] = "在大陸地圖上顯示"
L["Skyguard FlightMaster"] = "禦天者飛行管理員"
L["The alpha transparency of the icons"] = "圖示的透明程度"
L["The scale of the icons"] = "圖示的比例"
L["These settings control the look and feel of the FlightMaster icons."] = "這些設定控制飛行管理員圖示的外觀和風格。"


-- vim: ts=4 noexpandtab
