-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/handy-notes_flight-masters/localization/


local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "frFR")
if not L then return end

L["Aldor FlightMaster"] = "Maître de vol de l'Aldor"
L["Alliance FlightMaster"] = "Maître de vol de l'Alliance"
L["Create waypoint"] = "Creer un point de passage"
L["Druid FlightMaster"] = "Maître de vol cénarien"
L["Flight path lines"] = "Lignes des trajets de vol"
L["FlightMaster Icons"] = "Icônes de FlightMaster"
L["FlightMasters"] = "Maîtres de vol"
L["HandyNotes - FlightMasters"] = "HandyNotes - Maîtres de vol"
L["Horde FlightMaster"] = "Maître de vol de la Horde"
L["Icon Alpha"] = "Transparence des icônes"
L["Icon Scale"] = "Échelle des icônes"
L["Neutral FlightMaster"] = "Maître de vol neutre"
L["PvP FlightMaster"] = "Maître de vol JcJ"
L["Scryer FlightMaster"] = "Maître de vol des Clairvoyants"
L["Show all flightmasters instead of only those that you can use"] = "Affiche tous les maîtres de vol au lieu de n'afficher que ceux que vous pouvez utiliser."
L["Show both factions"] = "Afficher les deux factions"
L["Show flight path lines"] = " Afficher les trajets"
L["Show flight path lines on the world map"] = "Affiche les lignes des trajets de vol sur la carte du monde."
L["Show flight path lines on the zone maps as well"] = "Affiche les lignes des trajets de vol également sur les cartes des zones."
L["Show flightmasters on continent level maps as well"] = "Affiche les maîtres de vol également sur les cartes des continents."
L["Show in zones"] = "Afficher dans les zones"
L["Show on continent maps"] = "Cartes des continents"
L["Skyguard FlightMaster"] = "Maître de vol de la Garde-ciel"
L["The alpha transparency of the icons"] = "Définit la transparence des icônes."
L["The scale of the icons"] = "Définit l'échelle des icônes."
L["These settings control the look and feel of the FlightMaster icons."] = "Ces paramètres contrôlent l'apparence des icônes de FlightMaster."


-- vim: ts=4 noexpandtab
