-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/handy-notes_flight-masters/localization/


local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "zhCN")
if not L then return end

L["Aldor FlightMaster"] = "奥尔多飞行管理员"
L["Alliance FlightMaster"] = "联盟飞行管理员"
L["Create waypoint"] = "建立路径点"
L["Druid FlightMaster"] = "德鲁伊飞行管理员"
L["Flight path lines"] = "飞行路线"
L["FlightMaster Icons"] = "飞行管理员图标"
L["FlightMasters"] = "飞行管理员"
L["HandyNotes - FlightMasters"] = "HandyNotes - FlightMasters"
L["Horde FlightMaster"] = "部落飞行管理员"
L["Icon Alpha"] = "图标透明度"
L["Icon Scale"] = "图标缩放"
L["Neutral FlightMaster"] = "中立飞行管理员"
L["PvP FlightMaster"] = "PvP飞行管理员"
L["Scryer FlightMaster"] = "占星者飞行管理员"
L["Show all flightmasters instead of only those that you can use"] = "显示所有的飞行管理员而不仅仅是只显示你能用的"
L["Show both factions"] = "显示双方阵营"
L["Show flight path lines"] = "显示飞行路线"
L["Show flight path lines on the world map"] = "在世界地图上显示飞行路线"
L["Show flight path lines on the zone maps as well"] = "在区域地图上也显示飞行路线"
L["Show flightmasters on continent level maps as well"] = "在大陆地图上也显示飞行管理员的图标"
L["Show in zones"] = "区域内显示"
L["Show on continent maps"] = "在大陆地图上显示"
L["Skyguard FlightMaster"] = "天空卫队飞行管理员"
L["The alpha transparency of the icons"] = "图标的透明度值"
L["The scale of the icons"] = "图标的缩放值"
L["These settings control the look and feel of the FlightMaster icons."] = "这些设置控制着飞行管理员图标的外观与样式。"


-- vim: ts=4 noexpandtab
