-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/handy-notes_flight-masters/localization/


local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_FlightMasters", "ruRU")
if not L then return end

L["Aldor FlightMaster"] = "Распорядитель полетов Алдоров (Aldor)"
L["Alliance FlightMaster"] = "Распорядитель полетов Альянса"
L["Create waypoint"] = "Создать точку назначения"
L["Druid FlightMaster"] = "Распорядитель полетов Друидов"
L["Flight path lines"] = "Линии путей полёта"
L["FlightMaster Icons"] = "Значки Распорядителей полетов"
L["FlightMasters"] = "Распорядители полетов"
L["HandyNotes - FlightMasters"] = "HandyNotes - Рсапорядители полетов "
L["Horde FlightMaster"] = "Распорядитель полетов Орды"
L["Icon Alpha"] = "Прозрачность значка"
L["Icon Scale"] = "Масштаб значка"
L["Neutral FlightMaster"] = "Нейтральный Распорядитель полетов"
L["PvP FlightMaster"] = "ПвП Распорядитель полетов"
L["Scryer FlightMaster"] = "Распорядитель полетов Провидцев (Scryer)"
L["Show all flightmasters instead of only those that you can use"] = "Показывать всех Распорядителей полетов, а не только тех которых можно использовать"
L["Show both factions"] = "Показывать обе фракции"
L["Show flight path lines"] = "Показывать линии путей полётов"
L["Show flight path lines on the world map"] = "Показывать линии путей полётов на карте мира"
L["Show flight path lines on the zone maps as well"] = "Показывать линии путей полётов на картах зон"
L["Show flightmasters on continent level maps as well"] = "Показывать Распорядителей полётов на карте континентов"
L["Show in zones"] = "Показывать в зонах"
L["Show on continent maps"] = "Показывать на картах континентов"
L["Skyguard FlightMaster"] = "Распорядители полётов Стражей Небес (Skyguard)"
L["The alpha transparency of the icons"] = "Прозрачность значков"
L["The scale of the icons"] = "Масштаб значков"
L["These settings control the look and feel of the FlightMaster icons."] = "Эти настройки контролируют вид значков Распорядителей полётов."


-- vim: ts=4 noexpandtab
